apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-7jtufn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-7jtufn
  namespace: my-nginx-7jtufn
  labels:
    name: nginx-7jtufn
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-7jtufn
  template:
    metadata:
      namespace: my-nginx-7jtufn
      labels:
        name: nginx-7jtufn
    spec:
      containers:
      - name: nginx-7jtufn
        image: nginx
        ports:
        - containerPort: 80

